/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Recipient {
  'country' : string,
  'name' : string,
  'bankName' : string,
  'accountNumber' : string,
}
export interface Transfer {
  'id' : bigint,
  'fee' : number,
  'status' : boolean,
  'sourceCurrency' : string,
  'recipient' : Recipient,
  'sender' : Principal,
  'exchangeRate' : number,
  'destinationCurrency' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export interface UserProfile { 'country' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRecipient' : ActorMethod<[Recipient], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExchangeRates' : ActorMethod<[], Array<[string, number]>>,
  'getRecipients' : ActorMethod<[], Array<Recipient>>,
  'getTransferHistory' : ActorMethod<[], Array<Transfer>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transferMoney' : ActorMethod<[Recipient, number, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];