/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Recipient = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
});
export const Transfer = IDL.Record({
  'id' : IDL.Nat,
  'fee' : IDL.Float64,
  'status' : IDL.Bool,
  'sourceCurrency' : IDL.Text,
  'recipient' : Recipient,
  'sender' : IDL.Principal,
  'exchangeRate' : IDL.Float64,
  'destinationCurrency' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRecipient' : IDL.Func([Recipient], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExchangeRates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getRecipients' : IDL.Func([], [IDL.Vec(Recipient)], ['query']),
  'getTransferHistory' : IDL.Func([], [IDL.Vec(Transfer)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferMoney' : IDL.Func(
      [Recipient, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Recipient = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'country' : IDL.Text, 'name' : IDL.Text });
  const Transfer = IDL.Record({
    'id' : IDL.Nat,
    'fee' : IDL.Float64,
    'status' : IDL.Bool,
    'sourceCurrency' : IDL.Text,
    'recipient' : Recipient,
    'sender' : IDL.Principal,
    'exchangeRate' : IDL.Float64,
    'destinationCurrency' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRecipient' : IDL.Func([Recipient], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExchangeRates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getRecipients' : IDL.Func([], [IDL.Vec(Recipient)], ['query']),
    'getTransferHistory' : IDL.Func([], [IDL.Vec(Transfer)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferMoney' : IDL.Func(
        [Recipient, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };